### PR TITLE
Fixed an error in "cp_r" method where I couldn't pass as a parameter a...

### PR DESCRIPTION
**Pull request by giuliandrimba**
Fixed an error in "cp_r" method where I couldn't pass as a parameter a single file to be copied.

This code was throwing an error:

<pre>
fs.cp_r "path/to/single/file.yml", "path/to/single/copy.yml"
</pre>

The error message:

<pre>
fs.js:500
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOTDIR, not a directory 'path/to/single/file.yml'
</pre>

### CODE REVIEW

**Comment by arboleya** [comment]
What do you think about a new method `cp` which handles just files?

``` coffeescript
fsu.cp 'file.coffee', 'new_file.coffee'
fsu.cp_r 'templates/app', 'app/
```

Looks syntactic acceptable for me.

The `cp_r` may still handle files, through calling `cp`.

**Comment by giuliandrimba** [comment]
Great, I was thinking about creating only the "cp" method, wich copies everything I pass as a parameter (file or folder), and optionally, I could pass a parameter to copy recursively (or it could copy recursively whenever I pass a folder as parameter).

This way it would have just 1 method "cp" that handles diferrent input types.

But in the same time, it would change the API, and all the projects that uses "fs-util" will have to change the code.

What do you think? Is better to have 2 methods for different input types?

**Comment by arboleya** [comment]
I don't know, two methods seems ok to me, but when you think about a single method with optional flags, how do you imagine the method signature? `cp:(from, to, recursive)->` ?

**Comment by giuliandrimba** [comment]
I imagine the method without any flags. Anything that I pass as a parameter (file or folder) it would make a copy, and if it is a folder, it would copy recursively.

<pre>
cp:(from, to)
</pre>

But is just my opinion, 2 methods isn´t bad at all. I just prefer a method "copy" copying everything I pass as parameter.

**Comment by arboleya** [comment]
I see recursive methods a little dangerous to act in fully hybrid and automatic mode with it's own non-recursive behaviors. In case somethings goes wrong, the damage will be bigger.

A third parameter will removes this automation, but would pollute the signature a little.

`cp from, to, recursive` **X** `cp_r from, to`

**Comment by giuliandrimba** [comment]
Hum...I guess is better to have 2 methods instead.

<pre>cp from, to</pre>

and

<pre>cp_r from, to</pre>

I think the method name with the "r" is at the same time descriptive, as it shows that the method is recursive.

**Comment by giuliandrimba** [comment]
Hi, I wrote the test suite for the "cp" method.

**Comment by arboleya** [comment]
Nice one, I'll merge it as soon as I can.

Thanks for contributing. :)

**Pull request merged**
